-- Referencia del esquema ya ejecutado por el usuario. NO volver a ejecutarlo.
CREATE TABLE tecnicos (
  id_tecnico TEXT PRIMARY KEY,
  nombre_completo TEXT NOT NULL,
  especialidad TEXT,
  correo_electronico TEXT NOT NULL UNIQUE,
  telefono TEXT,
  estado TEXT NOT NULL DEFAULT 'ACTIVO',
  fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE usuarios (
  id_usuario TEXT PRIMARY KEY,
  correo TEXT NOT NULL UNIQUE,
  hash_contrasena TEXT NOT NULL,
  salt_contrasena TEXT NOT NULL,
  rol TEXT NOT NULL,
  id_tecnico TEXT REFERENCES tecnicos(id_tecnico) ON UPDATE CASCADE ON DELETE SET NULL,
  estado TEXT NOT NULL DEFAULT 'ACTIVO',
  intentos_fallidos INTEGER NOT NULL DEFAULT 0,
  bloqueado_hasta TIMESTAMPTZ,
  hash_sesion TEXT,
  expiracion_sesion TIMESTAMPTZ,
  debe_cambiar_contrasena BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE TABLE tickets (
  no_ticket TEXT PRIMARY KEY,
  fecha_hora_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  solicitante TEXT NOT NULL,
  sede TEXT NOT NULL,
  area_departamento TEXT NOT NULL,
  tipo TEXT NOT NULL,
  categoria TEXT NOT NULL,
  descripcion_detallada TEXT NOT NULL,
  adjuntos TEXT,
  prioridad TEXT NOT NULL DEFAULT 'NORMAL',
  estado TEXT NOT NULL DEFAULT 'CREATED',
  tecnico_asignado TEXT REFERENCES tecnicos(id_tecnico) ON UPDATE CASCADE ON DELETE SET NULL,
  fecha_asignacion TIMESTAMPTZ,
  fecha_resolucion TIMESTAMPTZ,
  resolucion TEXT,
  observaciones TEXT
);
CREATE TABLE historial_tickets (
  id_historial BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  no_ticket TEXT NOT NULL REFERENCES tickets(no_ticket) ON DELETE CASCADE,
  fecha_hora TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  tipo_evento TEXT NOT NULL,
  responsable TEXT NOT NULL,
  campo_modificado TEXT,
  valor_anterior TEXT,
  valor_nuevo TEXT,
  detalle TEXT
);
CREATE INDEX idx_tickets_estado ON tickets(estado);
CREATE INDEX idx_tickets_prioridad ON tickets(prioridad);
CREATE INDEX idx_tickets_tecnico ON tickets(tecnico_asignado);
CREATE INDEX idx_tickets_fecha_creacion ON tickets(fecha_hora_creacion DESC);
CREATE INDEX idx_historial_ticket ON historial_tickets(no_ticket);
CREATE INDEX idx_historial_fecha ON historial_tickets(fecha_hora DESC);
CREATE OR REPLACE FUNCTION actualizar_fecha_modificacion()
RETURNS TRIGGER AS $$
BEGIN
  NEW.fecha_actualizacion = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER trg_tecnicos_fecha_actualizacion
BEFORE UPDATE ON tecnicos
FOR EACH ROW EXECUTE FUNCTION actualizar_fecha_modificacion();
