import React, { useEffect, useMemo, useState } from 'react';
import { LayoutDashboard, Users, RefreshCw, LogOut, KeyRound, Ticket, Clock3, CheckCircle2, AlertTriangle, Search, ArrowUpRight, ChevronLeft, ChevronRight } from 'lucide-react';
import { STATES, summarizeTickets, filterTickets } from './admin.js';
import { AdminReports } from './AdminReports.jsx';
import { AdminUsers } from './AdminUsers.jsx';
import { TicketDetails } from './TicketDetails.jsx';
const labels = { CREADO: 'Recibidos', ASIGNADO: 'Asignados', 'EN PROCESO': 'En proceso', PENDIENTE: 'Pendientes', RESUELTO: 'Resueltos', CERRADO: 'Cerrados', CANCELADO: 'Cancelados' };
export function AdminDashboard({ api, session, onLogout, onChangePassword, onAuthError, onBusyChange, busy, error }) {
  const [tab, setTab] = useState('dashboard');
  const [tickets, setTickets] = useState([]);
  const [loading, setLoading] = useState(true);
  const [loaded, setLoaded] = useState(false);
  const [loadError, setLoadError] = useState('');
  const [revision, setRevision] = useState(0);
  const [updated, setUpdated] = useState('');
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState('');
  const [priority, setPriority] = useState('');
  const [page, setPage] = useState(1);
  const [selected, setSelected] = useState(null);
  useEffect(() => {
    let active = true; setLoading(true); setLoadError('');
    api('getTickets', {}, session.token).then(result => {
      if (!Array.isArray(result)) throw new Error('El servicio no devolvió una lista válida de tickets.');
      if (active) { setTickets(result); setLoaded(true); setUpdated(new Date().toLocaleString('es-GT', { year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' })); }
    }).catch(e => { if (active) { setLoadError(e.message); onAuthError(e); } }).finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, [api, session.token, revision]);
  const stats = useMemo(() => summarizeTickets(tickets), [tickets]);
  const filtered = useMemo(() => filterTickets(tickets, { search, status, priority }), [tickets, search, status, priority]);
  const pages = Math.max(1, Math.ceil(filtered.length / 10));
  const currentPage = Math.min(page, pages);
  const visible = filtered.slice((currentPage-1)*10, currentPage*10);
  function filterStatus(value) { setStatus(value); setPage(1); }
  const metrics = [ ['Total de tickets', stats.total, Ticket, '', 'Todas las solicitudes'], ['Abiertos', stats.open, Clock3, 'ABIERTOS', 'Recibidos, asignados, en proceso y pendientes'], ['Finalizados', stats.finished, CheckCircle2, 'FINALIZADOS', 'Resueltos y cerrados'], ['Cancelados', stats.cancelled, AlertTriangle, 'CANCELADO', 'Solicitudes canceladas'] ];
  return <section className="admin-dashboard" aria-label="Panel de administración"><header className="admin-hero"><div><p className="overline">CENTRO DE CONTROL · INFORMÁTICA</p><h2>Panel de administración</h2><p>Visibilidad de las solicitudes y accesos del equipo.</p></div><div className="admin-session"><span>ADMINISTRADOR</span><strong>{session.usuario.correo}</strong><div><button className="help-link" disabled={busy} onClick={onChangePassword}><KeyRound size={14}/>Contraseña</button><button className="help-link" disabled={busy} onClick={onLogout}><LogOut size={14}/>Cerrar sesión</button></div></div></header>
  <nav className="admin-tabs" aria-label="Secciones de administración"><button aria-current={tab === 'dashboard' ? 'page' : undefined} disabled={busy} onClick={() => setTab('dashboard')}><LayoutDashboard size={17}/>Dashboard</button><button aria-current={tab === 'users' ? 'page' : undefined} disabled={busy} onClick={() => setTab('users')}><Users size={17}/>Usuarios y técnicos</button><button aria-current={tab === 'reports' ? 'page' : undefined} disabled={busy} onClick={() => setTab('reports')}><LayoutDashboard size={17}/>Reportería</button></nav>{error && <div className="error" role="alert">{error}</div>}
  {tab === 'reports' ? <AdminReports tickets={tickets} loaded={loaded} loading={loading} loadError={loadError} updated={updated} onRefresh={() => setRevision(v => v+1)}/> : tab === 'users' ? <AdminUsers api={api} token={session.token} onAuthError={onAuthError} onBusyChange={onBusyChange}/> : <>
  <div className="admin-section-heading"><div><h3>Resumen de tickets</h3><p>{updated ? `Última actualización: ${updated}` : 'Datos del servicio de informática'}{loadError && loaded ? ' · Mostrando la última carga disponible' : ''}</p></div><button className="secondary" disabled={loading || busy} onClick={() => setRevision(v => v+1)}><RefreshCw size={15}/>{loading ? 'Cargando…' : 'Actualizar'}</button></div>{loadError && <div className="error" role="alert">{loadError}</div>}{loading && !loaded && <p className="admin-loading" role="status">Consultando tickets…</p>}
  <div className="metric-grid">{metrics.map(([label,value,Icon,filter,hint]) => <button className="metric-card" key={label} disabled={!loaded} onClick={() => filterStatus(filter)}><div><span>{label}</span><Icon size={20}/></div><strong>{loaded ? value : '—'}</strong><small>{hint}</small></button>)}</div>
  <div className="admin-charts"><section className="admin-card"><div className="admin-section-heading"><div><h3>Distribución por etapa</h3><p>Selecciona una etapa para filtrar la lista.</p></div></div><div className="stage-grid">{STATES.map(state => <button key={state} className={`stage-item ${status === state ? 'selected' : ''}`} disabled={!loaded} onClick={() => filterStatus(state)}><div><span>{labels[state]}</span><strong>{loaded ? stats.counts[state] : '—'}</strong></div><span className="stage-track"><span style={{ width: `${stats.total ? stats.counts[state] / stats.total * 100 : 0}%` }}/></span></button>)}</div></section><section className="admin-card attention-card"><AlertTriangle size={23}/><p>Requieren atención</p><strong>{loaded ? stats.urgent : '—'}</strong><span>Tickets abiertos de prioridad alta o crítica</span><div className="attention-buttons"><button disabled={!loaded} className="text-button" onClick={() => { filterStatus('ABIERTOS'); setPriority('CRITICA'); }}>Ver críticos <ArrowUpRight size={13}/></button><button disabled={!loaded} className="text-button" onClick={() => { filterStatus('ABIERTOS'); setPriority('ALTA'); }}>Ver prioridad alta <ArrowUpRight size={13}/></button></div></section></div>
  <section className="admin-card ticket-list"><div className="admin-section-heading"><div><h3>Explorar tickets</h3><p>{loaded ? `${filtered.length} de ${tickets.length} solicitudes` : 'Pendiente de carga'}</p></div>{(status || priority || search) && <button className="text-button" onClick={() => { setSearch(''); setPriority(''); filterStatus(''); }}>Limpiar filtros</button>}</div><div className="ticket-filters"><label className="field">Buscar<span className="input-wrap"><Search size={17}/><input value={search} onChange={e => { setSearch(e.target.value); setPage(1); }} placeholder="Ticket, solicitante, sede o técnico"/></span></label><label className="field">Estado<select value={status} onChange={e => filterStatus(e.target.value)}><option value="">Todos los estados</option><option value="ABIERTOS">Todos los abiertos</option><option value="FINALIZADOS">Todos los finalizados</option>{STATES.map(s => <option key={s} value={s}>{labels[s]}</option>)}</select></label><label className="field">Prioridad<select value={priority} onChange={e => { setPriority(e.target.value); setPage(1); }}><option value="">Todas</option>{['BAJA','MEDIA','ALTA','CRITICA'].map(p => <option key={p}>{p}</option>)}</select></label></div>
  <div className="admin-table-scroll"><table className="admin-table"><caption className="sr-only">Tickets del servicio de informática</caption><thead><tr><th>Ticket / fecha</th><th>Solicitante / sede</th><th>Estado</th><th>Prioridad</th><th>Técnico</th><th><span className="sr-only">Acción</span></th></tr></thead><tbody>{visible.map(t => <tr key={t.numeroTicket}><td><button className="ticket-link" onClick={() => setSelected(t)}>{t.numeroTicket}</button><small>{t.fechaCreacion}</small></td><td><strong>{t.solicitante}</strong><small>{t.sede}{t.area ? ` · ${t.area}` : ''}</small></td><td><span className="status-pill" data-status={t.estado}>{labels[t.estado] || t.estado}</span></td><td><span className="priority-pill" data-priority={t.prioridad}>{t.prioridad}</span></td><td>{t.nombreTecnicoAsignado || 'Sin asignar'}</td><td><button className="detail-button" aria-label={`Ver detalle ${t.numeroTicket}`} onClick={() => setSelected(t)}><ArrowUpRight size={18}/></button></td></tr>)}</tbody></table></div>{loaded && !filtered.length && <p className="admin-empty">{tickets.length ? 'No hay tickets que coincidan con los filtros.' : 'Todavía no hay tickets registrados.'}</p>}<div className="table-pagination"><span>Página {currentPage} de {pages}</span><div><button className="secondary" disabled={currentPage <= 1} onClick={() => setPage(currentPage-1)} aria-label="Página anterior"><ChevronLeft size={16}/></button><button className="secondary" disabled={currentPage >= pages} onClick={() => setPage(currentPage+1)} aria-label="Página siguiente"><ChevronRight size={16}/></button></div></div></section>
  </>}{selected && <TicketDetails key={selected.numeroTicket} ticket={selected} api={api} token={session.token} onAuthError={onAuthError} onBusyChange={onBusyChange} onUpdated={updatedTicket => { setSelected(updatedTicket); setTickets(current => current.map(t => t.numeroTicket === updatedTicket.numeroTicket ? updatedTicket : t)); }} onClose={() => setSelected(null)}/>}</section>;
}
