import React, { useMemo, useState } from 'react';
import { Download, RefreshCw, BarChart3 } from 'lucide-react';
import { reportData } from './reports.js';
import { STATES } from './admin.js';
import './reports.css';
const labels = {CREADO:'Recibidos',ASIGNADO:'Asignados','EN PROCESO':'En proceso',PENDIENTE:'Pendientes',RESUELTO:'Resueltos',CERRADO:'Cerrados',CANCELADO:'Cancelados'};
function Chart({title, subtitle, items, limit=8}) {
  const shown = items.slice(0,limit), max = Math.max(1,...shown.map(i=>i.value));
  return <section className="report-card"><h4>{title}</h4><p>{subtitle}{items.length>limit ? ` · Se muestran ${limit} de ${items.length}` : ''}</p>{shown.length ? <div className="report-bars">{shown.map((item,index)=><div className="report-bar" key={item.label}><div><span>{item.label}</span><strong>{item.value}</strong></div><svg viewBox="0 0 500 10" preserveAspectRatio="none" role="img" aria-label={`${item.label}: ${item.value}`}><rect width="500" height="10" rx="5" fill="#26352b"/><rect width={item.value/max*500} height="10" rx="5" fill={['#a3ff47','#70dba0','#d3ed87'][index%3]}/></svg></div>)}</div>:<p className="report-empty">Sin datos para este período.</p>}</section>;
}
export function AdminReports({tickets, loaded, loading, loadError, updated, onRefresh}) {
  const [from,setFrom]=useState(''),[to,setTo]=useState(''),[site,setSite]=useState('');
  const report=useMemo(()=>reportData(tickets,{from,to,site}),[tickets,from,to,site]);
  const sites=useMemo(()=>[...new Set(tickets.map(t=>t.sede).filter(Boolean))].sort(),[tickets]);
  const [generated,setGenerated]=useState('');
  const period=`${from || 'Inicio del registro'} — ${to || 'Última fecha disponible'}`;
  function exportPdf(){setGenerated(new Date().toLocaleString('es-GT')); requestAnimationFrame(()=>requestAnimationFrame(()=>window.print()));}
  const metrics=[['Tickets registrados',report.stats.total,'Según los filtros seleccionados'],['Abiertos',report.stats.open,'Recibidos, asignados, en proceso y pendientes'],['Finalizados',report.stats.finished,'Resueltos y cerrados'],['Cancelados',report.stats.cancelled,'Separados de los finalizados']];
  return <div className="reports"><div className="admin-section-heading report-controls"><div><h3><BarChart3 size={22}/> Reportería</h3><p>Indicadores para coordinar la atención y conocer la demanda.</p></div><div className="report-actions"><button className="secondary" disabled={loading} onClick={onRefresh}><RefreshCw size={15}/>{loading?'Actualizando…':'Actualizar'}</button><button className="secondary report-export" disabled={!loaded || loading || !!loadError || report.invalidRange || !report.stats.total} onClick={exportPdf}><Download size={16}/>Exportar PDF</button></div></div>
  <div className="report-controls report-filters"><label className="field">Creado desde<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="field">Creado hasta<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label className="field">Sede o agencia<select value={site} onChange={e=>setSite(e.target.value)}><option value="">Todas las sedes</option>{sites.map(s=><option key={s}>{s}</option>)}</select></label><button className="text-button" onClick={()=>{setFrom('');setTo('');setSite('');}}>Limpiar filtros</button></div>
  <p className="report-controls report-help">Para exportar, selecciona «Guardar como PDF» en el diálogo de impresión. El informe incluye las gráficas y los filtros aplicados.</p>
  {loadError && <div className="error" role="alert">{loadError} {loaded?'Se muestra la última carga disponible; actualiza antes de exportar.':''}</div>}
  {report.invalidRange && <div className="error" role="alert">La fecha inicial debe ser anterior o igual a la fecha final.</div>}
  {!loaded ? <p role="status">{loading?'Consultando datos para el informe…':'No hay datos cargados.'}</p> : !report.invalidRange && <article id="ticket-report">
  <header className="report-cover"><div><p className="overline">MUNI GUATE / SOPORTE TI</p><h3>Informe de atención</h3><p>Seguimiento de solicitudes y operación del equipo</p></div><span className="report-stamp">REPORTE ADMINISTRATIVO</span><dl><div><dt>Fecha de creación de tickets</dt><dd>{period}</dd></div><div><dt>Sede</dt><dd>{site || 'Todas las sedes'}</dd></div><div><dt>Datos actualizados</dt><dd>{updated || '—'}</dd></div></dl><p className="print-generated">Generado: {generated}</p></header>
  <div className="report-metrics">{metrics.map(([label,value,hint])=><section key={label}><span>{label}</span><strong>{value}</strong><small>{hint}</small></section>)}</div>
  <div className="report-insight"><strong>{report.rate===null?'—':`${report.rate}%`}</strong><span>de los tickets seleccionados están resueltos o cerrados. <b>{report.stats.urgent}</b> abiertos tienen prioridad alta o crítica.</span></div>
  {!report.stats.total && <p className="report-empty" role="status">No hay tickets que coincidan con estos filtros.</p>}
  <div className="report-grid"><Chart title="Estado de las solicitudes" subtitle="Estado actual · cantidad de tickets" items={STATES.map(s=>({label:labels[s],value:report.stats.counts[s]}))}/><Chart title="Prioridad de atención" subtitle="Prioridad actual · cantidad de tickets" items={report.priorities}/></div>
  <section className="report-section"><h3>Demanda del servicio</h3><div className="report-grid"><Chart title="Tickets por sede" subtitle="Sedes con mayor volumen" items={report.sites}/><Chart title="Categorías más frecuentes" subtitle="Sistemas y equipos · mayor volumen" items={report.categories}/><Chart title="Tipo de atención" subtitle="Valores registrados en los tickets" items={report.types}/><Chart title="Tickets por mes de creación" subtitle="Últimos 12 meses con registros · no representa fechas de resolución" items={report.months.slice(-12)} limit={12}/></div></section>
  <section className="report-section report-team"><h3>Distribución por técnico</h3><p>Asignación actual de los tickets seleccionados. Los finalizados no equivalen necesariamente a tickets resueltos por ese técnico.</p><div className="admin-table-scroll"><table className="admin-table"><caption className="sr-only">Carga de trabajo por técnico asignado</caption><thead><tr><th>Técnico</th><th>Total</th><th>Abiertos</th><th>Finalizados</th><th>Cancelados</th></tr></thead><tbody>{report.technicians.map(t=><tr key={t.id}><td>{t.name}</td><td>{t.total}</td><td>{t.open}</td><td>{t.finished}</td><td>{t.cancelled}</td></tr>)}</tbody></table></div></section>
  <footer className="report-footnote"><strong>Alcance del informe</strong><p>Los filtros de fecha corresponden a la creación del ticket, con ambos días incluidos. Los estados, prioridades y asignaciones reflejan la última carga disponible, no un corte histórico. Los porcentajes incluyen cancelados en el total. Las gráficas de sedes y categorías muestran hasta ocho elementos; los indicadores incluyen todos los tickets filtrados.</p>{report.unknownDates>0 && <p>{report.unknownDates} tickets sin fecha válida se incluyen en los totales, pero no en la gráfica mensual. Al filtrar por fecha se excluyen los registros sin fecha válida.</p>}<span>Municipalidad de Guatemala · Servicio de soporte TI</span></footer>
  </article>}
  </div>;
}
