import React, { useEffect, useRef, useState } from 'react';
import { X, ExternalLink } from 'lucide-react';
import { safeAttachmentUrl } from './admin.js';
import { TicketAssignment } from './TicketAssignment.jsx';
import { TicketPriority } from './TicketPriority.jsx';
import { TechnicianWork } from './TechnicianWork.jsx';
import { TicketFinalization } from './TicketFinalization.jsx';
export function TicketDetails({ mode = 'admin', ticket, onClose, api, token, onUpdated, onAuthError, onBusyChange }) {
  const dialog = useRef(null);
  const [saving, setSaving] = useState(false);
  const savingRef = useRef(false);
  function changeBusy(value) { savingRef.current = value; setSaving(value); onBusyChange(value); }
  function close() { if (!savingRef.current) onClose(); }
  useEffect(() => { dialog.current.showModal(); }, []);
  return <dialog className="admin-detail" ref={dialog} aria-labelledby="ticket-detail-title" onCancel={e => { if (savingRef.current) e.preventDefault(); else onClose(); }} onClick={e => { if (e.target === dialog.current) close(); }}><button className="close" disabled={saving} onClick={close} aria-label="Cerrar detalle"><X/></button><p className="overline">DETALLE DE SOLICITUD</p><h2 id="ticket-detail-title">{ticket.numeroTicket}</h2><div className="detail-badges"><span className="status-pill" data-status={ticket.estado}>{ticket.estado}</span><span className="priority-pill" data-priority={ticket.prioridad}>{ticket.prioridad}</span></div>{mode === 'admin' && <><TicketAssignment disabled={saving} api={api} token={token} ticket={ticket} onUpdated={onUpdated} onAuthError={onAuthError} onBusyChange={changeBusy}/><TicketPriority api={api} token={token} ticket={ticket} disabled={saving} onUpdated={onUpdated} onAuthError={onAuthError} onBusyChange={changeBusy}/></>}<dl className="tracking-details">{[['Solicitante',ticket.solicitante],['Sede',ticket.sede],['Área',ticket.area],['Tipo / categoría',[ticket.tipo,ticket.categoria].filter(Boolean).join(' · ')],['Técnico',ticket.nombreTecnicoAsignado || 'Sin asignar'],['Creación',ticket.fechaCreacion],['Asignación',ticket.fechaAsignacion || 'Pendiente'],['Resolución',ticket.fechaResolucion || 'Pendiente']].map(([label,value]) => <div key={label}><dt>{label}</dt><dd>{value || '—'}</dd></div>)}</dl><section className="detail-section"><h3>Descripción</h3><p>{ticket.descripcion || 'Sin descripción'}</p></section>{ticket.resolucion && <section className="detail-section"><h3>Resolución registrada</h3><p>{ticket.resolucion}</p></section>}{ticket.observaciones && <section className="detail-section"><h3>Observaciones internas</h3><p>{ticket.observaciones}</p></section>}{Array.isArray(ticket.adjuntos) && ticket.adjuntos.length > 0 && <section className="detail-section"><h3>Adjuntos</h3><ul className="detail-files">{ticket.adjuntos.map((file,i) => { const url = safeAttachmentUrl(file.url); return <li key={file.id || i}>{url ? <a href={url} target="_blank" rel="noopener noreferrer">{file.nombre || `Adjunto ${i+1}`}<ExternalLink size={14}/></a> : <span>{file.nombre || `Adjunto ${i+1}`} · Enlace no disponible</span>}</li>; })}</ul></section>}{mode === 'admin' && <TicketFinalization api={api} token={token} ticket={ticket} disabled={saving} onUpdated={onUpdated} onAuthError={onAuthError} onBusyChange={changeBusy}/>}<>{mode === 'technician' && <TechnicianWork api={api} token={token} ticket={ticket} disabled={saving} onUpdated={onUpdated} onAuthError={onAuthError} onBusyChange={changeBusy}/>}</></dialog>;
}
